// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Api.Services;

namespace Shop.Api.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20220307104859_AddSeedData2")]
    partial class AddSeedData2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shop.Api.Data.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Files");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "/images/glasses.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Path = "/images/headphones.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Path = "/images/pepsi.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Path = "/images/watch.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Path = "/images/capcake.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Path = "/images/cola.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Path = "/images/packet.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Path = "/images/parfume.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Path = "/images/soda.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Path = "/images/soda2.jpg"
                        });
                });

            modelBuilder.Entity("Shop.Api.Data.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Shop.Api.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InformationId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InformationId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Shop.Api.Data.OrderInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("OrderInformations");
                });

            modelBuilder.Entity("Shop.Api.Data.OrderLog", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "LogId");

                    b.HasIndex("LogId");

                    b.ToTable("OrderLogs");
                });

            modelBuilder.Entity("Shop.Api.Data.OrderProduct", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Shop.Api.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageId = 1,
                            Name = "Очки",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            ImageId = 2,
                            Name = "Наушники",
                            Price = 3500m
                        },
                        new
                        {
                            Id = 3,
                            ImageId = 3,
                            Name = "Pepsi-Cole",
                            Price = 350m
                        },
                        new
                        {
                            Id = 4,
                            ImageId = 4,
                            Name = "Очки",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 5,
                            ImageId = 5,
                            Name = "Кекс",
                            Price = 250m
                        },
                        new
                        {
                            Id = 6,
                            ImageId = 6,
                            Name = "Кола",
                            Price = 300m
                        },
                        new
                        {
                            Id = 7,
                            ImageId = 7,
                            Name = "Кофе",
                            Price = 750m
                        },
                        new
                        {
                            Id = 8,
                            ImageId = 8,
                            Name = "Духи",
                            Price = 15000m
                        },
                        new
                        {
                            Id = 9,
                            ImageId = 9,
                            Name = "Напиток",
                            Price = 500m
                        },
                        new
                        {
                            Id = 10,
                            ImageId = 10,
                            Name = "Candy Dry",
                            Price = 400m
                        });
                });

            modelBuilder.Entity("Shop.Api.Data.Order", b =>
                {
                    b.HasOne("Shop.Api.Data.OrderInformation", "Information")
                        .WithMany()
                        .HasForeignKey("InformationId");

                    b.Navigation("Information");
                });

            modelBuilder.Entity("Shop.Api.Data.OrderLog", b =>
                {
                    b.HasOne("Shop.Api.Data.Log", "Log")
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Api.Data.Order", "Order")
                        .WithMany("Logs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Shop.Api.Data.OrderProduct", b =>
                {
                    b.HasOne("Shop.Api.Data.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Api.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Shop.Api.Data.Product", b =>
                {
                    b.HasOne("Shop.Api.Data.FileModel", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Shop.Api.Data.Order", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
